### ISSUE TITLE
后端dockerfile

### ISSUE THREAD

**Issue by Alanyaeer** [Alanyaeer/oj-project-server-open#3]
@nanshaws 
后端的dockerfile是不是漏写了个 `.`

#2 
> 这是原本的
```dockerfile
# 略
# 运行命令
ENTRYPOINT ["java", "-jar", "/xx.jar"]
```
> 改成这个？
```dockerfile
# 略
# 运行命令
ENTRYPOINT ["java", "-jar", "./xx.jar"]
```

**Comment by nanshaws** [comment]
没问题吧，这涉及路径问题，之前复制命令 COPY xx.jar xx.jar   是将在dockerfile文件所在的目录下的 jar包复制到docker容器根目录下的，所以直接目录是/xx.jar是没有问题的，同时，使用 `./xx.jar` 也是可行的，因为 Dockerfile 中执行 `ENTRYPOINT` 或 `CMD` 时，默认的工作目录就是容器的根目录。

**Comment by Alanyaeer** [comment]
看来我得回顾一下docker的知识了
